artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local: D:/News-Article-Sorting-with-Deep-Learning-NLP-Project/nlp projecrt.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion